In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# Sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
# Vocabulary size
voc_size = 10000 # Hyperparameter

# One Hot Representation

In [13]:
onehot_rep = [one_hot(words, voc_size) for words in sent]
print(onehot_rep)

[[9730, 2871, 7408, 6352], [9730, 2871, 7408, 8513], [9730, 6418, 7408, 6028], [3248, 4084, 2084, 4920, 6774], [3248, 4084, 2084, 4920, 4640], [4203, 9730, 705, 7408, 7403], [2399, 2584, 7869, 4920]]


One hot encoder show the index of getting 1 for that particulr word

# Word Embedding Represntation

In [8]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
# Pre-padding
sent_length = 8 # Hyperparameter
embedded_docs = pad_sequences(onehot_rep, padding="pre", maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 9730 2871 7408 6352]
 [   0    0    0    0 9730 2871 7408 8513]
 [   0    0    0    0 9730 6418 7408 6028]
 [   0    0    0 3248 4084 2084 4920 6774]
 [   0    0    0 3248 4084 2084 4920 4640]
 [   0    0    0 4203 9730  705 7408 7403]
 [   0    0    0    0 2399 2584 7869 4920]]


In [16]:
# Feature Dimensions
dim = 10 # Hyperparameter , 10 because our sentence size is small

model = Sequential()
# Embedding layer act like word2vec and convert the vectors and 10 indicate how many feature you want in each vector
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile("adam", "mse")
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
# 'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0, 9730, 2871, 7408, 6352], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

array([[ 0.02420756,  0.02306268,  0.04960282, -0.00854678, -0.0280973 ,
         0.02012387, -0.03065536,  0.00460125,  0.00487161, -0.02155936],
       [ 0.02420756,  0.02306268,  0.04960282, -0.00854678, -0.0280973 ,
         0.02012387, -0.03065536,  0.00460125,  0.00487161, -0.02155936],
       [ 0.02420756,  0.02306268,  0.04960282, -0.00854678, -0.0280973 ,
         0.02012387, -0.03065536,  0.00460125,  0.00487161, -0.02155936],
       [ 0.02420756,  0.02306268,  0.04960282, -0.00854678, -0.0280973 ,
         0.02012387, -0.03065536,  0.00460125,  0.00487161, -0.02155936],
       [ 0.03250447, -0.04320952,  0.04894124, -0.02071166,  0.0432817 ,
         0.02149763,  0.00789299, -0.03937318, -0.0407189 ,  0.03598752],
       [ 0.04454093,  0.04752607,  0.00800165,  0.01931251, -0.02689745,
        -0.0047732 ,  0.03418643,  0.01288933,  0.0479283 ,  0.04072206],
       [-0.01802851, -0.01537425,  0.04748876,  0.03294964,  0.00773482,
         0.04409761,  0.0415936 , -0.01443747

In [19]:
print(model.predict(embedded_docs)[0])

[[ 0.02420756  0.02306268  0.04960282 -0.00854678 -0.0280973   0.02012387
  -0.03065536  0.00460125  0.00487161 -0.02155936]
 [ 0.02420756  0.02306268  0.04960282 -0.00854678 -0.0280973   0.02012387
  -0.03065536  0.00460125  0.00487161 -0.02155936]
 [ 0.02420756  0.02306268  0.04960282 -0.00854678 -0.0280973   0.02012387
  -0.03065536  0.00460125  0.00487161 -0.02155936]
 [ 0.02420756  0.02306268  0.04960282 -0.00854678 -0.0280973   0.02012387
  -0.03065536  0.00460125  0.00487161 -0.02155936]
 [ 0.03250447 -0.04320952  0.04894124 -0.02071166  0.0432817   0.02149763
   0.00789299 -0.03937318 -0.0407189   0.03598752]
 [ 0.04454093  0.04752607  0.00800165  0.01931251 -0.02689745 -0.0047732
   0.03418643  0.01288933  0.0479283   0.04072206]
 [-0.01802851 -0.01537425  0.04748876  0.03294964  0.00773482  0.04409761
   0.0415936  -0.01443747 -0.04364238 -0.02809385]
 [-0.04852532 -0.03040657  0.02802889 -0.03074342  0.02139732  0.0496775
  -0.03223697 -0.00713753  0.04834798  0.00119555]]
